### ISSUE TITLE
Simplify urls for single/base entity

### ISSUE THREAD

**Issue by luxumbra** [evildmp/Arkestra#1]
When the system is in single entity mode, root urls for news & events and contacts & people still display sitename.com/entity/entity-name/news-and-events, etc. This also happens with the base entity. 

When viewing a news item, the system appears to revert back to sitename.com/news/news-article-slug.

It would improve urls for sites that only have the one entity for news/events publishing.

**Comment by evildmp** [comment]
It's done!

There are a few tweaks still to be made, and no doubt some bugs to be discovered, but now the system:
- will take URLs such as /contact or /news-and-events to be asking for information about the site's base entity 
- will generate URLs for entity related information intelligently, so that it uses:
  - /contact for the base entity
    */contact/entity_slug for the others

Neat!
