### ISSUE TITLE
Person slugs include title PK, not text

### ISSUE THREAD

**Issue by evildmp** [evildmp/Arkestra#95]
For example:

```
5-daniele-procida
```

instead of 

```
mr-daniele-procida
```

Likely to have been introduced in #68 #70

**Comment by darbula** [comment]
This should be fixed on this [line](https://github.com/evildmp/Arkestra/blob/develop/contacts_and_people/admin.py#L233). 

[Documentation](https://docs.djangoproject.com/en/dev/ref/contrib/admin/#django.contrib.admin.ModelAdmin.prepopulated_fields) states _prepopulated_fields doesn’t accept DateTimeField, ForeignKey, nor ManyToManyField fields_ so consider removing title from the slug. 

Removing title can be justified because slug is not changing and title could be changing these two could eventually become out of sync, oth name could be changed, also...
